### ISSUE TITLE
Could you provide the trace generator? 

### ISSUE THREAD

**Issue by YangZhou1997** [icsa-caps/ccKVS#2]
Hi, 

I am trying to conduct the experiment done in your eurosys paper; however, I found the trace generator is missing -- only trace splitter is there. Could you share the trace generator? 

Thanks!

**Comment by akatsarakis** [comment]
Hello Yang,

You may find a similar version of the trace generator that was used in ccKVS in the following repo.
https://github.com/akatsarakis/trace-generator
I recommend using the simple trace generator.

All the best,
-Antonis
